services:
  - type: web
    name: jurassihealth
    runtime: docker
    dockerfilePath: ./Clinica-JURASSIHEALTH/Dockerfile
    dockerContext: ./Clinica-JURASSIHEALTH
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__Default
        sync: false
      - key: Auth__SecretKey
        sync: false
      - key: AdminPadrao__Email
        sync: false
      - key: AdminPadrao__SenhaHash
        sync: false
      - key: Email__Smtp__Host
        sync: false
      - key: Email__Smtp__Port
        value: 587
      - key: Email__Smtp__User
        sync: false
      - key: Email__Smtp__Password
        sync: false
      - key: Email__Smtp__FromEmail
        sync: false
      - key: Email__Smtp__FromName
        value: Clinica JurassiHealth
      - key: Email__Smtp__EnableSsl
        value: true
